-- Live EGX radar persistence
-- Applied to Supabase project jhubsrbfiqjxdgngnwaq on 2026-09-29.

create table if not exists public.live_radar_runs (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  session_date date not null,
  universe_count integer not null default 0,
  advancers integer not null default 0,
  decliners integer not null default 0,
  unchanged integer not null default 0,
  breadth_ratio numeric(8,6),
  median_change_pct numeric(12,6),
  signal_count integer not null default 0,
  top_score numeric(8,3),
  interval_seconds numeric(8,2),
  source text not null default 'tradingview'
);

create index if not exists live_radar_runs_session_time_idx
  on public.live_radar_runs (session_date, observed_at desc);

create table if not exists public.live_radar_signals (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  session_date date not null,
  ticker text not null,
  name text,
  sector text,
  stage text not null check (stage in ('WATCH','TRIGGERING','BREAKOUT')),
  score numeric(8,3) not null,
  close numeric(18,6) not null,
  change_pct numeric(12,6),
  interval_seconds numeric(8,2),
  price_delta_pct numeric(12,6),
  volume_delta numeric(24,4),
  interval_turnover numeric(24,4),
  volume_pace numeric(12,6),
  rvol10 numeric(12,6),
  close_location numeric(12,8),
  hod_distance_pct numeric(12,6),
  new_hod boolean not null default false,
  velocity_1m_pct numeric(12,6),
  velocity_3m_pct numeric(12,6),
  relative_strength_pct numeric(12,6),
  positive_intervals_5 integer,
  higher_low boolean,
  compression_pct numeric(12,6),
  market_breadth_ratio numeric(12,8),
  market_median_change_pct numeric(12,6),
  market_regime text,
  reasons jsonb not null default '[]'::jsonb,
  alert_sent boolean not null default false,
  source text not null default 'tradingview'
);

create index if not exists live_radar_signals_session_time_idx
  on public.live_radar_signals (session_date, observed_at desc);
create index if not exists live_radar_signals_ticker_time_idx
  on public.live_radar_signals (ticker, observed_at desc);
create index if not exists live_radar_signals_stage_score_idx
  on public.live_radar_signals (stage, score desc, observed_at desc);

create table if not exists public.live_radar_latest (
  ticker text primary key,
  updated_at timestamptz not null default now(),
  session_date date not null,
  name text,
  sector text,
  stage text check (stage in ('WATCH','TRIGGERING','BREAKOUT')),
  score numeric(8,3) not null,
  close numeric(18,6) not null,
  change_pct numeric(12,6),
  interval_seconds numeric(8,2),
  price_delta_pct numeric(12,6),
  volume_delta numeric(24,4),
  interval_turnover numeric(24,4),
  volume_pace numeric(12,6),
  rvol10 numeric(12,6),
  close_location numeric(12,8),
  hod_distance_pct numeric(12,6),
  new_hod boolean not null default false,
  velocity_1m_pct numeric(12,6),
  velocity_3m_pct numeric(12,6),
  relative_strength_pct numeric(12,6),
  positive_intervals_5 integer,
  higher_low boolean,
  compression_pct numeric(12,6),
  market_breadth_ratio numeric(12,8),
  market_median_change_pct numeric(12,6),
  market_regime text,
  reasons jsonb not null default '[]'::jsonb,
  source text not null default 'tradingview'
);

create index if not exists live_radar_latest_score_idx
  on public.live_radar_latest (score desc, updated_at desc);

alter table public.live_radar_runs enable row level security;
alter table public.live_radar_signals enable row level security;
alter table public.live_radar_latest enable row level security;
